### ISSUE TITLE
mergeする際にrspecによる検証を行うようにする

### ISSUE THREAD

**Issue by nakajima97** [yudai-nakajima/letter-box-backend#21]
# 概要
mergeする際にrspecで検証するためのGithub Actionsを追加する

# 終了条件
- [x] Github Actionsを作成する

# 方法
ネットで`Github actions rspec`とか調べないで自力でgithub actions書いてみよう

# 困ったこと
## rails db:createでdb connection errrorが発生する
ローカルでdocker-composeを実行しても発生しないエラー

### 解決策
docker-composeを使わないようにした

docker-composeを使うこと前提で作成したworkflowは以下の通り
```yaml
name: Ruby

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup docker
        shell: bash
        run: |
          # イメージのビルド
          docker-compose build
          docker-compose up -d
        env:
          RAILS_ENV: test

      - name: DB Create
        shell: bash
        run: |
          # ここで失敗する
          # Mysql2::Error::ConnectionError: Can't connect to MySQL server on 'db' (115)
          # ローカルのubutnuでは成功するので謎
          docker-compose run api rails db:create

      - name: Run RSpec
        shell: bash
        run: |
          docker-compose run api /bin/bash -c "cd ../myapp && bundle exec rspec"
          # docker-compose run api bundle exec rspec
        env:
          RAILS_ENV: test

```
